collections:
  thoughts:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "thoughts"
    values:
      layout: thought
      author:
        name: "Tom Stuart & Tiffany Conroy"
exclude:
  - Makefile
  - _thoughts/Makefile
  - _thoughts/tests.js
  - _thoughts/queue-tests.js
  - _thoughts/backlog-tests.js
plugins:
  - jekyll-feed
  - jekyll-redirect-from
feed:
  collections:
    thoughts:
      path: "/thoughts.xml"
