collections:
  writings:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "writings"
    values:
      author:
        name: "Tom Stuart & Tiffany Conroy"
exclude:
  - Makefile
  - _writings/Makefile
  - _writings/tests.js
  - _writings/queue-tests.js
  - _writings/backlog-tests.js
plugins:
  - jekyll-feed
feed:
  collections:
    writings:
      path: "/writings.xml"
